### PR TITLE
Add indication for items that change the player's appearance -- issue #97

### PR DESCRIPTION
**Pull request by moyzone**
### Summary
This PR adds a small visual indication for items that change the player's appearance in the item description. Specifically, it checks if the item's type is `primemachin` and, if so, displays a relevant icon next to the item description.

### Related Issues
This addresses issue #97 , which requests a way to identify items that alter the player's appearance.

### Detailed Description
- Updated `item-description.vue` to include a check for `item.item_type === 'primemachin'`.

### Additional Notes
- Translations for the indication text were added for both English and French.

### CODE REVIEW

**Comment by Sceat** [comment]
Thanks a lot for your help, can you post a screenshot of the results ?

**Comment by moyzone** [comment]
Screenshot 2024-05-30 172238
Screenshot 2024-05-30 172238




Hi here is the attached sreenshot of what I have done. I have added a small cloth hanger icon on the inventory items that change the appearance

**Comment by moyzone** [comment]
hello does this need any improvements?

**Comment by Sceat** [comment]
We have a discord yes https://discord.gg/aresrpg

Concerning the feature it's not on the inventory but on the `item-description.vue` that the indicator should be, a simple italic line "This item will change your appearance"

**Pull request closed without merging**
